name = "MRTools"
uuid = "94d9ee1b-bcc7-4953-b220-10612eb99093"
authors = ["MR"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
